// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


import type { ReactNode } from 'react'
import { Tajawal } from 'next/font/google'
const tajawal = Tajawal({
  weight: ['400', '700'],
  subsets: ['arabic']
});

import { Footer } from '../components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { Header2 } from '../components/Header2';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eibaa Website',
  description: 'إباء أبو طه',
}

export default function RootLayout({ children }: { children: ReactNode }): JSX.Element {

  return (
    <html lang="ar">

      <body dir="rtl" className={tajawal.className}>
        <Header2 />


        {children}

        <Footer />
      </body>

    </html>
  )
}
